platform :ios, '8.0'
use_frameworks!

target 'ReactionSDKExample' do
    #pod 'Google/CloudMessaging'

    pod 'Reaction'
end

pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end