# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
#use_frameworks!

target 'ReactionSDK' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

  # Pods for ReactionSDK
  pod 'Google'
  pod 'Google/CloudMessaging'
  pod 'AtomSDK'

  target 'ReactionSDKTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
